### ISSUE TITLE
Clone & Pod Problem

### ISSUE THREAD

**Issue by OnurVar** [respoke/sample-respoke-ios#5]
Hello,

I'm having this problem.

[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `RespokeTests`..

 #  from /Users/onurvar/Storage/Project/RespokeSample/sample-respoke-ios/Podfile:5
 #  -------------------------------------------
 #  

>  target :RespokeTests, :exclusive => true do
>  #    pod 'KIF', '~> 3.0', :configurations => ['Debug']
>  #  -------------------------------------------

[!] xcodeproj was renamed to `project`. Please use that from now on.

Can you guys help ?
Thanks.

**Comment by chadxz** [comment]
It's probably using a podspec format that was for pre 1.0 cocoapods. If you update the cocoapods to the new format it probably won't complain. I don't have the time to look at this right now but that's the direction I would go if I were to try to fix it.
